### ISSUE TITLE
Failed to activate the support-gbk package

### ISSUE THREAD

**Issue by zouyun5152** [ibigbug/support-gbk#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.3
**Thrown From**: [support-gbk](https://github.com/ibigbug/support-gbk) package, v1.1.0

### Stack Trace

Failed to activate the support-gbk package

```
At ENOENT, no such file or directory '/Users/zouyunpeng/Downloads/css.css'

Error: ENOENT, no such file or directory '/Users/zouyunpeng/Downloads/css.css'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:355:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
    at Object.module.exports.detectFileSync (/Users/zouyunpeng/.atom/packages/support-gbk/node_modules/chardet/index.js:84:27)
    at handleBuffer (/Users/zouyunpeng/.atom/packages/support-gbk/lib/support-gbk.coffee:28:24)
    at /Users/zouyunpeng/.atom/packages/support-gbk/lib/support-gbk.coffee:16:16
    at WorkspaceView.module.exports.WorkspaceView.eachEditorView (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:92:9)
    at Object.module.exports.convert (/Users/zouyunpeng/.atom/packages/support-gbk/lib/support-gbk.coffee:15:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "rain-ui",
      "rain-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
file-icons, v1.5.1
rain-syntax, v0.1.0
rain-ui, v0.3.0
support-gbk, v1.1.0

# Dev
No dev packages
```

**Comment by ibigbug** [comment]
Try the latest version.
